# brownie-config.yaml
# Colócalo en la raíz del proyecto Brownie, junto a contracts/, scripts/, tests/

dotenv: .env

compiler:
  solc:
    version: 0.8.20
    optimizer:
      enabled: true
      runs: 200

networks:
  development:
    gas_price: 2000000000
    host: http://127.0.0.1:8545
    chainid: 1337

  sepolia:
    host: https://sepolia.infura.io/v3/${infura_project_id}
    chainid: 11155111
